"""
Nifty 500 Equivalent Stocks List
================================

Top 500 most actively traded stocks from NSE equity database.
Generated on: 2025-11-18 10:52:23
Total stocks: 500
"""

NIFTY_500_STOCKS = [
    'IDEA', 'SAGILITY', 'YESBANK', 'SUZLON', 'SOUTHBANK', 'TATAGOLD', 'FILATFASH', 'RPOWER', 'PCJEWELLER', 'GOLDBEES',
    'ADANIPOWER', 'SILVERBEES', 'IDFCFIRSTB', 'CANBK', 'TATSILV', 'ETERNAL', 'GTLINFRA', 'UTKARSHBNK', 'SAIL', 'TATASTEEL',
    'JPPOWER', 'IDBI', 'SAMMAANCAP', 'EPACKPEB', 'HDFCBANK', 'PNB', 'NMDC', 'MAHABANK', 'IOC', 'MOTHERSON',
    'UNIONBANK', 'BEL', 'SCI', 'MRPL', 'BHEL', 'NATIONALUM', 'ASHOKLEY', 'BANKINDIA', 'METALIETF', 'ITC',
    'RBLBANK', 'ICICIBANK', 'UJJIVANSFB', 'GMRAIRPORT', 'UCOBANK', 'INFIBEAM', 'RTNPOWER', 'POWERGRID', 'EASEMYTRIP', 'HFCL',
    'FEDERALBNK', 'SALASAR', 'GATECH', 'SBIN', 'RAMASTEEL', 'CENTRALBK', 'BANDHANBNK', 'SBC', 'BANKBARODA', 'RELIANCE',
    'NHPC', 'VEDL', 'LTF', 'ITBEES', 'BHARTIARTL', 'IOB', 'NBCC', 'INDUSTOWER', 'REDINGTON', 'TMPV',
    'JYOTISTRUC', 'JIOFIN', 'BPCL', 'ARIHANTCAP', 'JAYNECOIND', 'INFY', 'HINDCOPPER', 'ONGC', 'NTPC', 'DCBBANK',
    'SILVERCASE', 'LIQUIDCASE', 'SHRIRAMFIN', 'IRB', 'SARVESHWAR', 'GAIL', 'VBL', 'CHENNPETRO', 'WIPRO', 'HINDALCO',
    'HCC', 'GOLDCASE', 'COALINDIA', 'FCL', 'BAJFINANCE', 'VIKRAN', 'NSLNISP', 'SETFGOLD', 'EDELWEISS', 'PAISALO',
    'URBANCO', 'VMM', 'IEX', 'SWIGGY', 'RECLTD', 'GOLDIETF', 'ZEEL', 'BCG', 'KALAMANDIR', 'NYKAA',
    'IFCI', 'FCSSOFT', 'SILVERIETF', 'KELLTONTEC', 'ABCAPITAL', 'PFC', 'INOXWIND', 'BELRISE', 'IREDA', 'BSE',
    'ATHERENERG', 'IRFC', 'NIFTYBEES', 'AXISBANK', 'JAINREC', 'HDFCGOLD', 'DAVANGERE', 'BAJAJHIND', 'PARADEEP', 'AURIGROW',
    'TFCILTD', 'CUB', 'SHAH', 'HDFCSILVER', 'ADANIGREEN', 'HINDPETRO', 'VINCOFE', 'TATAPOWER', 'INDUSINDBK', 'MANAPPURAM',
    'FIVESTAR', 'VAKRANGEE', 'HBLENGINE', 'NTPCGREEN', 'TATACAP', 'TRIDENT', 'PFS', 'SEPC', 'ABFRL', 'EMBDL',
    'GPPL', 'MCLOUD', 'HINDZINC', 'GARUDA', 'JMFINANCIL', 'GREENPOWER', 'NCC', 'PHARMABEES', 'DELHIVERY', 'PSUBNKBEES',
    'HUDCO', 'YATRA', 'DISHTV', 'BIOCON', 'UNITECH', 'ZEEMEDIA', 'BLS', 'MSUMI', 'IXIGO', 'WELSPUNLIV',
    'APOLLO', 'EQUITASBNK', 'SBFC', 'VIKASLIFE', 'SANDUMA', 'EXXARO', 'CUPID', 'CRAMC', 'BSOFT', 'PPLPHARMA',
    'SYRMA', 'LOWVOLIETF', 'TARIL', 'PSB', 'ALOKINDS', 'BAJAJHFL', 'RVNL', 'ATALREAL', 'CROMPTON', 'ESSENTIA',
    'CANHLIFE', 'PFOCUS', 'J&KBANK', 'INDHOTEL', 'GPIL', 'CGCL', 'AUBANK', 'NIVABUPA', 'GREAVESCOT', 'RHETAN',
    'SWSOLAR', 'JINDALSAW', 'AVANTEL', 'ALLCARGO', 'JKTYRE', 'GMDCLTD', 'CESC', 'UPL', 'PAYTM', 'MUFIN',
    'NETWORK18', 'M&MFIN', 'HEG', 'PGEL', 'KALYANKJIL', 'OILIETF', 'KTKBANK', 'TPHQ', 'RENUKA', 'SAKUMA',
    'ITCHOTELS', 'IOLCP', 'DABUR', 'KITEX', 'LIQUIDBEES', 'KARURVYSYA', 'TCS', 'DEVYANI', 'MICEL', 'CGPOWER',
    'BLISSGVS', 'SJVN', 'PRECWIRE', 'KOTAKBANK', 'PARAGMILK', 'IGL', 'TDPOWERSYS', 'MIDCAPETF', 'FORTIS', 'LAURUSLABS',
    'FISCHER', 'TATAINVEST', 'HARDWYN', 'JAICORPLTD', 'ALPL30IETF', 'VAIBHAVGBL', 'MOSCHIP', 'VASCONEQ', 'VIKASECO', 'M&M',
    'HDFCLIFE', 'ANANTRAJ', 'NETWEB', 'FILATEX', 'METAL', 'SILVER', 'ADANIPORTS', 'MOTISONS', 'ONEPOINT', 'JSWCEMENT',
    'SHAREINDIA', 'SBISILVER', 'INDIANB', 'DLF', 'DAMCAPITAL', 'HCLTECH', 'LTGILTBEES', 'AWL', 'JISLJALEQS', 'INOXGREEN',
    'DRREDDY', 'DCW', 'MODEFENCE', 'JSWENERGY', 'OIL', 'JUBLFOOD', 'SONACOMS', 'FSL', 'LEMONTREE', 'CDSL',
    'MAXHEALTH', 'LICI', 'EXIDEIND', 'SWANCORP', 'MMTC', 'PACEDIGITK', 'IIFL', 'TIMETECHNO', 'GMRP&UI', 'ADVANCE',
    'LT', 'AMBUJACEM', 'GOLD1', 'BANCOINDIA', 'LLOYDSENGG', 'PETRONET', 'TI', 'STLNETWORK', 'IRCON', 'GLOBE',
    'GRAPHITE', 'POLICYBZR', 'SHRINGARMS', 'ENGINERSIN', 'GODREJCP', 'SUBEXLTD', 'SILVERETF', 'TECHM', 'RTNINDIA', 'NEWGEN',
    'CIPLA', 'ADANIENSOL', 'FABTECH', 'GMBREW', 'NDL', 'SUNPHARMA', 'COFORGE', 'PATELENG', 'PENIND', 'AXISGOLD',
    'SIGACHI', 'APTUS', 'JINDALSTEL', 'PREMIERENE', 'AARTIIND', 'ADANIENT', 'LGEINDIA', 'POONAWALLA', 'STLTECH', 'CONCOR',
    'STEELXIND', 'BHARATWIRE', 'PVTBANIETF', 'NLCINDIA', 'PRICOLLTD', 'CHOLAFIN', 'HINDUNILVR', 'HONASA', 'AFIL', 'BHAGERIA',
    'AUROPHARMA', 'JTLIND', 'BDL', 'RAIN', 'BLSE', 'SEQUENT', 'MANAKCOAT', 'JSWSTEEL', 'MOTILALOFS', 'SMALLCAP',
    'DIACABS', 'ASIANPAINT', 'MID150CASE', 'RBA', 'QUADFUTURE', 'TATACONSUM', 'ARSSBL', 'LODHA', 'WELCORP', 'SBICARD',
    'PATANJALI', 'BLACKBUCK', 'GKENERGY', 'ASIANTILES', 'DBREALTY', 'MBEL', 'TEJASNET', 'ABLBL', 'ALPHA', 'ELECTCAST',
    'MOBIKWIK', 'LICHSGFIN', 'MARICO', 'KRBL', 'COHANCE', 'NAZARA', 'MOREPENLAB', '3IINFOLTD', 'PNBHOUSING', 'UNITDSPR',
    'MIDCAPIETF', 'SKYGOLD', 'GRSE', 'GOLDETF', 'SHANTIGOLD', 'MTNL', 'JSWINFRA', 'APOLLOTYRE', 'GENUSPOWER', 'BAJAJFINSV',
    'AXITA', 'SAMBHV', 'MARKSANS', 'TTML', 'MON100', 'KIRLOSENG', 'HATHWAY', 'SAMHI', 'CCL', 'BHARATFORG',
    'ZAGGLE', 'JAMNAAUTO', 'ACMESOLAR', 'TICL', 'DHANBANK', 'CASTROLIND', 'SILVER1', 'STAR', 'FEDFINA', 'LUPIN',
    'ICICIPRULI', 'SYNCOMF', 'AXISILVER', 'IGIL', 'RCF', 'HITECH', 'HSCL', 'SINDHUTRAD', 'VOLTAS', 'TRANSRAILL',
    'PTC', 'NAUKRI', 'INDORAMA', 'SONATSOFTW', 'INVENTURE', 'TARC', 'GSFC', 'INTELLECT', 'BAJAJCON', 'VTL',
    'GATECHDVR', 'SBILIFE', 'SUNDARAM', 'MOSMALL250', 'CPSEETF', 'RAJRATAN', 'ATGL', 'HDFCSML250', 'PARAS', 'PSPPROJECT',
    'NAM-INDIA', 'GSLSU', 'LLOYDSENT', 'TVSMOTOR', 'MOM30IETF', 'VCL', 'KPIGREEN', 'SHREEJISPG', 'IIFLCAPS', 'DUCON',
    'MGEL', 'REGAAL', 'SHRIRAMPPS', 'VIKRAMSOLR', 'RICOAUTO', 'TEXRAIL', 'WAAREERTL', 'LATENTVIEW', 'COCHINSHIP', 'KNRCON',
    'RKFORGE', 'KAMDHENU', 'ASHOKA', 'TRENT', 'RELIGARE', 'BORORENEW', 'CHAMBLFERT', 'MAZDOCK', 'HAL', 'EIEL',
    'HYUNDAI', 'XCHANGING', 'URJA', 'NESTLEIND', 'ABDL', 'KFINTECH', 'GRMOVER', 'JYOTICNC', 'KHAICHEM', 'MOGOLD',
    'TITAN', 'RALLIS', 'AVTNPL', 'KEC', 'INDRAMEDCO', 'RUBICON', 'DREDGECORP', 'LOTUSDEV', 'SETFNIF50', 'UTIBANKETF',
    'GALLANTT', 'WAAREEENER', 'PARSVNATH', 'UNOMINDA', 'MOREALTY', 'GOKULAGRO', 'MFSL', 'EMIL', 'HLEGLAS', 'GOLDSHARE'
]

# Total stocks: 500
print(f"Nifty 500 equivalent stocks loaded: {len(NIFTY_500_STOCKS)} stocks")
