# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events/schemas/v1/candle_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events/schemas/v1/candle_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#events/schemas/v1/candle_data.proto\x12 realtime_yahoo_service.events.v1\"\x80\x03\n\nCandleData\x12\x16\n\x0eschema_version\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x12\n\ntrade_date\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x12\n\nprev_close\x18\x05 \x01(\x01\x12\x12\n\nopen_price\x18\x06 \x01(\x01\x12\x12\n\nhigh_price\x18\x07 \x01(\x01\x12\x11\n\tlow_price\x18\x08 \x01(\x01\x12\x13\n\x0b\x63lose_price\x18\t \x01(\x01\x12\x0e\n\x06volume\x18\n \x01(\x03\x12\x19\n\x0c\x64\x65livery_qty\x18\x0b \x01(\x03H\x00\x88\x01\x01\x12\x19\n\x0c\x64\x65livery_per\x18\x0c \x01(\x01H\x01\x88\x01\x01\x12\x13\n\x0b\x64\x61ta_source\x18\r \x01(\t\x12\x13\n\x06series\x18\x0e \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08\x65xchange\x18\x0f \x01(\tH\x03\x88\x01\x01\x42\x0f\n\r_delivery_qtyB\x0f\n\r_delivery_perB\t\n\x07_seriesB\x0b\n\t_exchangeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.schemas.v1.candle_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDLEDATA']._serialized_start=74
  _globals['_CANDLEDATA']._serialized_end=458
# @@protoc_insertion_point(module_scope)
