# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events/schemas/v1/fetch_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events/schemas/v1/fetch_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$events/schemas/v1/fetch_status.proto\x12 realtime_yahoo_service.events.v1\"\x8f\x04\n\x0b\x46\x65tchStatus\x12\x16\n\x0eschema_version\x18\x01 \x01(\x05\x12\x14\n\x0cpublisher_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12H\n\x06status\x18\x04 \x01(\x0e\x32\x38.realtime_yahoo_service.events.v1.FetchStatus.StatusType\x12\x19\n\x11symbols_succeeded\x18\x05 \x01(\x05\x12\x16\n\x0esymbols_failed\x18\x06 \x01(\x05\x12\x15\n\rtotal_symbols\x18\x07 \x01(\x05\x12\x12\n\nbatch_size\x18\x08 \x01(\x05\x12\x12\n\nrate_limit\x18\t \x01(\x05\x12\x1a\n\rerror_message\x18\n \x01(\tH\x00\x88\x01\x01\x12\x16\n\x0e\x66\x61iled_symbols\x18\x0b \x03(\t\x12\x19\n\x11\x66\x65tch_duration_ms\x18\x0c \x01(\x03\x12\x16\n\x0euptime_seconds\x18\r \x01(\x03\x12\x1e\n\x16total_events_published\x18\x0e \x01(\x03\"j\n\nStatusType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07STARTED\x10\x01\x12\x0b\n\x07HEALTHY\x10\x02\x12\x0c\n\x08\x44\x45GRADED\x10\x03\x12\r\n\tUNHEALTHY\x10\x04\x12\x0b\n\x07STOPPED\x10\x05\x12\x0b\n\x07\x43RASHED\x10\x06\x42\x10\n\x0e_error_messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.schemas.v1.fetch_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FETCHSTATUS']._serialized_start=75
  _globals['_FETCHSTATUS']._serialized_end=602
  _globals['_FETCHSTATUS_STATUSTYPE']._serialized_start=478
  _globals['_FETCHSTATUS_STATUSTYPE']._serialized_end=584
# @@protoc_insertion_point(module_scope)
