# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events/schemas/v1/market_breadth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events/schemas/v1/market_breadth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&events/schemas/v1/market_breadth.proto\x12 realtime_yahoo_service.events.v1\"\xf9\x02\n\rMarketBreadth\x12\x16\n\x0eschema_version\x18\x01 \x01(\x05\x12\x12\n\nindex_name\x18\x02 \x01(\t\x12\x12\n\ntrade_date\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x10\n\x08\x61\x64vances\x18\x05 \x01(\x05\x12\x10\n\x08\x64\x65\x63lines\x18\x06 \x01(\x05\x12\x11\n\tunchanged\x18\x07 \x01(\x05\x12\x14\n\x0ctotal_stocks\x18\x08 \x01(\x05\x12\x10\n\x08\x61\x64_ratio\x18\t \x01(\x01\x12\x17\n\x0fsentiment_score\x18\n \x01(\x01\x12\x1b\n\x0e\x61vg_pct_change\x18\x0b \x01(\x01H\x00\x88\x01\x01\x12\x1a\n\rnew_highs_52w\x18\x0c \x01(\x05H\x01\x88\x01\x01\x12\x19\n\x0cnew_lows_52w\x18\r \x01(\x05H\x02\x88\x01\x01\x12\x13\n\x0b\x64\x61ta_source\x18\x0e \x01(\tB\x11\n\x0f_avg_pct_changeB\x10\n\x0e_new_highs_52wB\x0f\n\r_new_lows_52wb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.schemas.v1.market_breadth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETBREADTH']._serialized_start=77
  _globals['_MARKETBREADTH']._serialized_end=454
# @@protoc_insertion_point(module_scope)
